- name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Subway-Surfers-Mod
          path: ./*-aligned-debugSigned.apk
          # THE FIX: This prevents GitHub from double-zipping your file
          compression-level: 0
